### ISSUE TITLE
Provisioned Entries in Smart Start Disappeared after upgrade to 3.4.2

### ISSUE THREAD

**Issue by smarthomeaf** [hassio-addons/addon-zwave-js-ui#654]
Upgraded my JWAVE-JS UI last evening and noticed this morning that all my provisioned entries in smart start disappeared.  I had 60+ entries in there.  I am restoring to before the upgrade to see if that fixes the issue.

I am able to add new ones and they remain.

**Comment by smarthomeaf** [comment]
Reverting back to 3.4.1 fixed the issue.  This was also reported on the hass core.  https://github.com/home-assistant/core/issues/114950

**Comment by mikejhill** [comment]
Supposedly resolved in zwave-js 12.5.4, included in zwave-js-ui 9.10.3, but hearing mixed reports: https://github.com/zwave-js/node-zwave-js/issues/6755

Looks like the dependency bump was already applied here. Looking forward to the next add-on release to test.

**Comment by alvinchen1** [comment]
Anyone still having this issue since the release of 3.5.0?  Also rolled back to 3.4.1 to resolve the issue temporarily, but based upon the reports, not sure I want to update to 3.5.0 yet.

**Comment by ekrunch** [comment]
I've got mine back under 3.50,. Notes on that...

I was on 3.4.2 and everything was blank even though the entries were still in the database, upgrading to 3.5.0 didn't fix it.

I reverted back to 3.4.1 and then upgraded straight to 3.5.0 and now everything is there again. So going from 3.4.1 directly to 3.5.0 seems to work.

**Comment by PhAzE-Variance** [comment]
Is there a fix that doesn't involve restoring to an old version? Was this a database edit that just needs to be undone?

**Comment by mrrobotnic** [comment]
Same thing here going from 3.4.2 to 3.5.0 I don't see any of the entries in the Smart Start area still.  I have full HA backups from when I was running 3.4.1 but not the direct 3.4.1 zwave-js backup unfortunately since that was weeks ago so hoping it is something that can be resolved with a future update.
